# Generated by Django 5.0.3 on 2026-01-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_missing_bookmark_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
    ]
